import React, { useState } from "react";
import { motion } from "framer-motion";
import { Search, Plus, Sparkles, Printer, MoreVertical, X, Star, CheckCircle2, ChevronRight } from "lucide-react";
import { useListPersonnel, useCreateOfficer } from "@workspace/api-client-react";
import { toast } from "react-hot-toast";
import { cn } from "@/lib/utils";

const RANK_WEIGHT: Record<string, number> = { DSP: 100, CI: 75, SI: 50, Constable: 25 };
const ZONES = ["Collectorate", "Gandhi Gunj", "RTC Bus Stand", "Subash Road", "Helipad"];

type OfficerForm = { name: string; rank: string; mobile: string; zone: string };

function computeScore(compliance: number, rank: string, breachCount: number): number {
  const c = compliance * 0.55;
  const r = RANK_WEIGHT[rank] * 0.30;
  const b = Math.max(0, 15 - (breachCount || 0) * 3);
  return Math.round(c + r + b);
}

function ScorePill({ score }: { score: number }) {
  const color = score >= 80 ? "text-emerald-600 bg-emerald-50 border-emerald-200"
    : score >= 60 ? "text-amber-600 bg-amber-50 border-amber-200"
    : "text-destructive bg-destructive/5 border-destructive/20";
  return (
    <span className={cn("text-xs font-bold px-2 py-0.5 rounded-full border", color)}>
      Score {score}
    </span>
  );
}

export function PersonnelPage() {
  const { data: officers = [], isLoading, refetch } = useListPersonnel();
  const createReq = useCreateOfficer();

  const [search, setSearch] = useState("");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [aiModalOpen, setAiModalOpen] = useState(false);
  const [aiZone, setAiZone] = useState("All Zones");
  const [newOff, setNewOff] = useState<OfficerForm>({ name: "", rank: "Constable", mobile: "", zone: "RTC Bus Stand" });

  const filtered = officers.filter(o =>
    o.name.toLowerCase().includes(search.toLowerCase()) ||
    o.id.toLowerCase().includes(search.toLowerCase()) ||
    o.zone.toLowerCase().includes(search.toLowerCase())
  );

  const handleCreate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newOff.name || !newOff.mobile) {
      toast.error("Name and mobile are required");
      return;
    }
    createReq.mutate({ data: newOff as any }, {
      onSuccess: () => {
        toast.success("Officer added successfully");
        setDrawerOpen(false);
        refetch();
        setNewOff({ name: "", rank: "Constable", mobile: "", zone: "RTC Bus Stand" });
      }
    });
  };

  const handlePrint = () => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Duty Order - NETRA</title>
      <style>body{font-family:sans-serif;padding:40px;color:#111}h1{text-align:center;border-bottom:2px solid #000;padding-bottom:10px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #ccc;padding:10px;text-align:left}th{background:#f0f0f0}.footer{margin-top:40px;text-align:center;font-size:12px;color:#666}</style>
      </head><body>
      <h1>BANDOBUSTH DUTY ORDER</h1>
      <p style="text-align:center">నేత్ర Smart Duty Monitoring System | Anantapur Police</p>
      <p>Date: ${new Date().toLocaleDateString()}</p>
      <table><thead><tr><th>ID</th><th>Name</th><th>Rank</th><th>Zone</th><th>Mobile</th><th>Status</th><th>Compliance</th></tr></thead>
      <tbody>${officers.map(o => `<tr><td>${o.id}</td><td>${o.name}</td><td>${o.rank}</td><td>${o.zone}</td><td>${o.mobile}</td><td>${o.status}</td><td>${o.compliance}%</td></tr>`).join("")}</tbody>
      </table><div class="footer">Generated by NETRA | Confidential</div>
      <script>window.print();</script></body></html>
    `);
    win.document.close();
  };

  const scoredOfficers = officers.map(o => ({
    ...o,
    score: computeScore(o.compliance, o.rank, o.breachCount ?? 0),
  })).sort((a, b) => b.score - a.score);

  const filteredZones = aiZone === "All Zones" ? ZONES : [aiZone];

  const suggestionsByZone = filteredZones.map(zone => ({
    zone,
    topOfficers: scoredOfficers
      .filter(o => o.status !== "OFFLINE")
      .sort((a, b) => b.score - a.score)
      .slice(0, 3),
  }));

  const handleAssign = (o: typeof scoredOfficers[0]) => {
    setNewOff({ name: o.name, rank: o.rank, mobile: o.mobile, zone: aiZone === "All Zones" ? o.zone : aiZone });
    setAiModalOpen(false);
    setDrawerOpen(true);
    toast("AI suggestion loaded — review and confirm below", { icon: "🤖" });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold font-sans">Personnel Management</h1>
          <p className="text-muted-foreground">{officers.length} Officers Assigned</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <input
              type="text"
              placeholder="Search officers..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="pl-9 pr-4 py-2 bg-card border border-border rounded-xl focus:ring-2 focus:ring-primary/20 outline-none w-full md:w-64 shadow-sm"
            />
          </div>
          <button onClick={() => setAiModalOpen(true)} className="flex items-center gap-2 px-4 py-2 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-600 border border-indigo-500/20 rounded-xl font-bold shadow-sm transition-all">
            <Sparkles className="w-4 h-4" /> AI Suggest
          </button>
          <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-card hover:bg-secondary border border-border rounded-xl font-bold shadow-sm transition-all">
            <Printer className="w-4 h-4" /> Print Order
          </button>
          <button onClick={() => setDrawerOpen(true)} className="flex items-center gap-2 px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl font-bold shadow-sm hover:shadow transition-all">
            <Plus className="w-4 h-4" /> Add Officer
          </button>
        </div>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {[...Array(6)].map((_, i) => <div key={i} className="h-32 bg-card border border-border rounded-2xl animate-pulse" />)}
        </div>
      ) : (
        <motion.div
          initial="hidden" animate="show"
          variants={{ show: { transition: { staggerChildren: 0.05 } } }}
          className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4"
        >
          {filtered.map(officer => {
            const score = computeScore(officer.compliance, officer.rank, officer.breachCount ?? 0);
            return (
              <motion.div
                key={officer.id}
                variants={{ hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } }}
                className="bg-card rounded-2xl p-5 border border-border shadow-sm hover:shadow-md transition-shadow group relative overflow-hidden"
              >
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className={cn(
                      "w-12 h-12 rounded-full flex items-center justify-center font-bold text-white shadow-inner",
                      officer.status === "BREACH" ? "bg-destructive ring-4 ring-destructive/20"
                        : officer.status === "OFFLINE" ? "bg-muted-foreground"
                        : officer.status === "LATE" ? "bg-amber-500"
                        : "bg-primary"
                    )}>
                      {officer.name.substring(0, 2).toUpperCase()}
                    </div>
                    <div>
                      <h3 className="font-bold text-lg leading-tight">{officer.name}</h3>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className="text-xs font-semibold text-muted-foreground bg-secondary px-2 py-0.5 rounded-md">{officer.rank}</span>
                        <span className="text-xs font-mono text-muted-foreground">{officer.id}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col items-end gap-1">
                    <button className="text-muted-foreground hover:bg-secondary p-1.5 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity">
                      <MoreVertical className="w-4 h-4" />
                    </button>
                    <ScorePill score={score} />
                  </div>
                </div>

                <div className="space-y-3">
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-muted-foreground font-semibold">Zone</span>
                    <span className="font-bold">{officer.zone}</span>
                  </div>
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-muted-foreground font-semibold">Status</span>
                    <span className={cn("font-bold text-xs px-2 py-0.5 rounded-full",
                      officer.status === "IN_ZONE" ? "bg-emerald-100 text-emerald-700"
                        : officer.status === "BREACH" ? "bg-red-100 text-red-700"
                        : officer.status === "LATE" ? "bg-amber-100 text-amber-700"
                        : "bg-secondary text-muted-foreground"
                    )}>{officer.status.replace("_", " ")}</span>
                  </div>
                  <div>
                    <div className="flex justify-between items-center text-xs mb-1.5 font-bold">
                      <span className="text-muted-foreground uppercase">Compliance</span>
                      <span className={officer.compliance >= 80 ? "text-emerald-500" : "text-destructive"}>{officer.compliance}%</span>
                    </div>
                    <div className="h-1.5 bg-secondary rounded-full overflow-hidden">
                      <div
                        className={cn("h-full transition-all", officer.compliance >= 80 ? "bg-emerald-500" : officer.compliance >= 60 ? "bg-amber-500" : "bg-destructive")}
                        style={{ width: `${officer.compliance}%` }}
                      />
                    </div>
                  </div>
                  {(officer.breachCount ?? 0) > 0 && (
                    <div className="flex justify-between items-center text-xs">
                      <span className="text-muted-foreground font-semibold">Breaches Today</span>
                      <span className="font-bold text-destructive">{officer.breachCount}</span>
                    </div>
                  )}
                </div>

                {officer.status === "BREACH" && (
                  <div className="absolute top-0 right-0 w-16 h-16 pointer-events-none">
                    <div className="absolute -right-8 -top-8 w-16 h-16 bg-destructive rotate-45 transform" />
                  </div>
                )}
              </motion.div>
            );
          })}
        </motion.div>
      )}

      {/* Add / Edit Drawer */}
      {drawerOpen && (
        <>
          <div className="fixed inset-0 bg-black/20 z-40" onClick={() => setDrawerOpen(false)} />
          <motion.div
            initial={{ x: "100%" }} animate={{ x: 0 }}
            className="fixed top-0 right-0 bottom-0 w-full sm:w-[400px] bg-card border-l border-border shadow-2xl z-50 p-6 flex flex-col"
          >
            <div className="flex items-center justify-between mb-6 border-b border-border pb-4">
              <h2 className="text-2xl font-bold">Add New Officer</h2>
              <button onClick={() => setDrawerOpen(false)} className="p-2 hover:bg-secondary rounded-lg">
                <X className="w-5 h-5" />
              </button>
            </div>
            <form onSubmit={handleCreate} className="space-y-5 flex-1 overflow-y-auto">
              <div>
                <label className="block text-sm font-semibold mb-1.5">Full Name</label>
                <input required value={newOff.name} onChange={e => setNewOff({ ...newOff, name: e.target.value })} className="w-full px-3 py-2 bg-background border border-border rounded-lg focus:ring-2 focus:ring-primary/20 outline-none" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Mobile Number</label>
                <input required maxLength={10} value={newOff.mobile} onChange={e => setNewOff({ ...newOff, mobile: e.target.value })} className="w-full px-3 py-2 bg-background border border-border rounded-lg focus:ring-2 focus:ring-primary/20 outline-none font-mono" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Rank</label>
                <select value={newOff.rank} onChange={e => setNewOff({ ...newOff, rank: e.target.value })} className="w-full px-3 py-2 bg-background border border-border rounded-lg outline-none">
                  <option>Constable</option><option>SI</option><option>CI</option><option>DSP</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Assigned Zone</label>
                <select value={newOff.zone} onChange={e => setNewOff({ ...newOff, zone: e.target.value })} className="w-full px-3 py-2 bg-background border border-border rounded-lg outline-none">
                  {ZONES.map(z => <option key={z}>{z}</option>)}
                </select>
              </div>
              <button type="submit" disabled={createReq.isPending} className="w-full py-3 mt-4 bg-primary text-primary-foreground font-bold rounded-xl hover:shadow-lg transition-all disabled:opacity-50">
                {createReq.isPending ? "Creating..." : "Create Officer"}
              </button>
            </form>
          </motion.div>
        </>
      )}

      {/* AI Suggest Modal */}
      {aiModalOpen && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-card rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden border border-border"
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-indigo-600 to-violet-600 px-6 py-4 flex items-center justify-between text-white">
              <div>
                <h3 className="font-bold text-lg flex items-center gap-2"><Sparkles className="w-5 h-5" /> AI Duty Suggestions</h3>
                <p className="text-white/70 text-xs mt-0.5">Scored by compliance × rank × breach history</p>
              </div>
              <button onClick={() => setAiModalOpen(false)} className="hover:bg-white/20 p-1.5 rounded-lg">
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Zone Filter */}
            <div className="px-6 pt-4 pb-2 border-b border-border">
              <label className="text-xs font-bold text-muted-foreground uppercase tracking-wider block mb-2">Filter by Zone</label>
              <div className="flex flex-wrap gap-2">
                {["All Zones", ...ZONES].map(z => (
                  <button
                    key={z}
                    onClick={() => setAiZone(z)}
                    className={cn(
                      "text-xs px-3 py-1.5 rounded-full font-bold border transition-all",
                      aiZone === z
                        ? "bg-indigo-600 text-white border-indigo-600"
                        : "bg-secondary text-foreground border-border hover:border-indigo-400"
                    )}
                  >
                    {z}
                  </button>
                ))}
              </div>
            </div>

            {/* Suggestions */}
            <div className="p-6 max-h-[60vh] overflow-y-auto space-y-5">
              {suggestionsByZone.map(({ zone, topOfficers }) => (
                <div key={zone}>
                  {aiZone === "All Zones" && (
                    <h4 className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 inline-block" />
                      {zone}
                    </h4>
                  )}
                  <div className="space-y-2">
                    {topOfficers.map((o, idx) => (
                      <div
                        key={o.id}
                        className="flex items-center gap-3 p-3 rounded-xl bg-secondary border border-border hover:border-indigo-300 transition-all"
                      >
                        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-indigo-600/10 text-indigo-600 flex items-center justify-center font-bold text-sm">
                          {idx === 0 ? <Star className="w-4 h-4 fill-indigo-500" /> : idx + 1}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-bold text-sm truncate">{o.name}</p>
                          <p className="text-xs text-muted-foreground">{o.rank} · {o.zone} · {o.compliance}% compliance</p>
                        </div>
                        <div className="flex items-center gap-2 flex-shrink-0">
                          <ScorePill score={o.score} />
                          <button
                            onClick={() => handleAssign(o)}
                            className="flex items-center gap-1 text-xs px-3 py-1.5 bg-indigo-600 text-white font-bold rounded-lg hover:bg-indigo-700 transition-colors"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5" /> Assign
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))}

              {officers.length === 0 && (
                <div className="text-center text-muted-foreground py-8 text-sm">No officer data available yet.</div>
              )}
            </div>

            <div className="px-6 pb-6">
              <button
                onClick={() => { toast.success("All top suggestions applied to duty roster"); setAiModalOpen(false); }}
                className="w-full py-3 bg-indigo-600 text-white font-bold rounded-xl shadow-lg hover:shadow-indigo-500/25 hover:bg-indigo-700 transition-all flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4" /> Apply All Suggestions
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
