import React, { useState } from "react";
import { motion } from "framer-motion";
import { Search, Plus, Sparkles, Printer, MoreVertical, X } from "lucide-react";
import { useListPersonnel, useCreateOfficer } from "@workspace/api-client-react";
import { toast } from "react-hot-toast";
import { cn } from "@/lib/utils";

export function PersonnelPage() {
  const { data: officers = [], isLoading, refetch } = useListPersonnel();
  const createReq = useCreateOfficer();
  
  const [search, setSearch] = useState("");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [aiModalOpen, setAiModalOpen] = useState(false);

  // New Officer State
  const [newOff, setNewOff] = useState({ name: "", rank: "Constable", mobile: "", zone: "RTC Bus Stand" });

  const filtered = officers.filter(o => 
    o.name.toLowerCase().includes(search.toLowerCase()) || 
    o.id.toLowerCase().includes(search.toLowerCase()) ||
    o.zone.toLowerCase().includes(search.toLowerCase())
  );

  const handleCreate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newOff.name || !newOff.mobile) {
      toast.error("Name and mobile are required");
      return;
    }
    createReq.mutate({ data: newOff as any }, {
      onSuccess: () => {
        toast.success("Officer added successfully");
        setDrawerOpen(false);
        refetch();
        setNewOff({ name: "", rank: "Constable", mobile: "", zone: "RTC Bus Stand" });
      }
    });
  };

  const handlePrint = () => {
    const win = window.open('', '_blank');
    if (!win) return;
    
    const html = `
      <html>
        <head>
          <title>Duty Order - NETRA</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #111; }
            h1 { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ccc; padding: 10px; text-align: left; }
            th { background: #f0f0f0; }
            .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <h1>BANDOBUSTH DUTY ORDER</h1>
          <p style="text-align: center;">నేత్ర Smart Duty Monitoring System | Anantapur Police</p>
          <p>Date: ${new Date().toLocaleDateString()}</p>
          <table>
            <thead>
              <tr><th>ID</th><th>Name</th><th>Rank</th><th>Zone</th><th>Mobile</th></tr>
            </thead>
            <tbody>
              ${officers.map(o => `<tr><td>${o.id}</td><td>${o.name}</td><td>${o.rank}</td><td>${o.zone}</td><td>${o.mobile}</td></tr>`).join('')}
            </tbody>
          </table>
          <div class="footer">Generated by NETRA | Confidential</div>
          <script>window.print();</script>
        </body>
      </html>
    `;
    win.document.write(html);
    win.document.close();
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold font-sans">Personnel Management</h1>
          <p className="text-muted-foreground">{officers.length} Active Officers Assigned</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <input 
              type="text" 
              placeholder="Search officers..." 
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="pl-9 pr-4 py-2 bg-card border border-border rounded-xl focus:ring-2 focus:ring-primary/20 outline-none w-full md:w-64 shadow-sm"
            />
          </div>
          <button onClick={() => setAiModalOpen(true)} className="flex items-center gap-2 px-4 py-2 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-600 border border-indigo-500/20 rounded-xl font-bold shadow-sm transition-all">
            <Sparkles className="w-4 h-4" /> AI Suggest
          </button>
          <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-card hover:bg-secondary border border-border rounded-xl font-bold shadow-sm transition-all">
            <Printer className="w-4 h-4" /> Print Order
          </button>
          <button onClick={() => setDrawerOpen(true)} className="flex items-center gap-2 px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl font-bold shadow-sm hover:shadow transition-all">
            <Plus className="w-4 h-4" /> Add Officer
          </button>
        </div>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {[...Array(6)].map((_, i) => <div key={i} className="h-32 bg-card border border-border rounded-2xl animate-pulse" />)}
        </div>
      ) : (
        <motion.div 
          initial="hidden" animate="show"
          variants={{ show: { transition: { staggerChildren: 0.05 } } }}
          className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4"
        >
          {filtered.map(officer => (
            <motion.div 
              key={officer.id}
              variants={{ hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } }}
              className="bg-card rounded-2xl p-5 border border-border shadow-sm hover:shadow-md transition-shadow group relative overflow-hidden"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className={cn("w-12 h-12 rounded-full flex items-center justify-center font-bold text-white shadow-inner", 
                    officer.status === 'BREACH' ? 'bg-destructive ring-4 ring-destructive/20' : 'bg-primary'
                  )}>
                    {officer.name.substring(0, 2).toUpperCase()}
                  </div>
                  <div>
                    <h3 className="font-bold text-lg leading-tight">{officer.name}</h3>
                    <div className="flex items-center gap-2 mt-0.5">
                      <span className="text-xs font-semibold text-muted-foreground bg-secondary px-2 py-0.5 rounded-md">{officer.rank}</span>
                      <span className="text-xs font-mono text-muted-foreground">{officer.id}</span>
                    </div>
                  </div>
                </div>
                <button className="text-muted-foreground hover:bg-secondary p-1.5 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity">
                  <MoreVertical className="w-4 h-4" />
                </button>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between items-center text-sm">
                  <span className="text-muted-foreground font-semibold">Zone</span>
                  <span className="font-bold">{officer.zone}</span>
                </div>
                <div>
                  <div className="flex justify-between items-center text-xs mb-1.5 font-bold">
                    <span className="text-muted-foreground uppercase">Compliance</span>
                    <span className={officer.compliance >= 80 ? "text-emerald-500" : "text-destructive"}>{officer.compliance}%</span>
                  </div>
                  <div className="h-1.5 bg-secondary rounded-full overflow-hidden">
                    <div 
                      className={cn("h-full", officer.compliance >= 80 ? "bg-emerald-500" : "bg-destructive")} 
                      style={{ width: `${officer.compliance}%` }} 
                    />
                  </div>
                </div>
              </div>
              
              {officer.status === 'BREACH' && (
                <div className="absolute top-0 right-0 w-16 h-16 pointer-events-none">
                  <div className="absolute -right-8 -top-8 w-16 h-16 bg-destructive rotate-45 transform" />
                </div>
              )}
            </motion.div>
          ))}
        </motion.div>
      )}

      {/* Add Drawer */}
      {drawerOpen && (
        <>
          <div className="fixed inset-0 bg-black/20 z-40" onClick={() => setDrawerOpen(false)} />
          <motion.div 
            initial={{ x: '100%' }} animate={{ x: 0 }}
            className="fixed top-0 right-0 bottom-0 w-full sm:w-[400px] bg-card border-l border-border shadow-2xl z-50 p-6 flex flex-col"
          >
            <h2 className="text-2xl font-bold mb-6 border-b border-border pb-4">Add New Officer</h2>
            <form onSubmit={handleCreate} className="space-y-5 flex-1 overflow-y-auto">
              <div>
                <label className="block text-sm font-semibold mb-1.5">Full Name</label>
                <input required value={newOff.name} onChange={e => setNewOff({...newOff, name: e.target.value})} className="w-full px-3 py-2 bg-background border border-border rounded-lg focus:ring-2 focus:ring-primary/20 outline-none" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Mobile Number</label>
                <input required maxLength={10} value={newOff.mobile} onChange={e => setNewOff({...newOff, mobile: e.target.value})} className="w-full px-3 py-2 bg-background border border-border rounded-lg focus:ring-2 focus:ring-primary/20 outline-none font-mono" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Rank</label>
                <select value={newOff.rank} onChange={e => setNewOff({...newOff, rank: e.target.value})} className="w-full px-3 py-2 bg-background border border-border rounded-lg outline-none">
                  <option>Constable</option><option>SI</option><option>CI</option><option>DSP</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-semibold mb-1.5">Assigned Zone</label>
                <select value={newOff.zone} onChange={e => setNewOff({...newOff, zone: e.target.value})} className="w-full px-3 py-2 bg-background border border-border rounded-lg outline-none">
                  <option>Collectorate</option><option>Gandhi Gunj</option><option>RTC Bus Stand</option><option>Subash Road</option><option>Helipad</option>
                </select>
              </div>
              <button type="submit" disabled={createReq.isPending} className="w-full py-3 mt-4 bg-primary text-primary-foreground font-bold rounded-xl hover:shadow-lg transition-all disabled:opacity-50">
                {createReq.isPending ? "Creating..." : "Create Officer"}
              </button>
            </form>
          </motion.div>
        </>
      )}

      {/* AI Modal Mock */}
      {aiModalOpen && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="bg-card rounded-2xl shadow-2xl max-w-md w-full overflow-hidden border border-border">
            <div className="bg-indigo-600 px-6 py-4 flex items-center justify-between text-white">
              <h3 className="font-bold flex items-center gap-2"><Sparkles className="w-5 h-5"/> AI Duty Suggestions</h3>
              <button onClick={() => setAiModalOpen(false)} className="hover:bg-white/20 p-1 rounded-lg"><X className="w-5 h-5"/></button>
            </div>
            <div className="p-6 text-center text-muted-foreground">
              <p className="mb-4 text-sm">Our AI analyzes past compliance, rank weights, and availability to suggest optimal deployments.</p>
              <div className="p-4 bg-secondary rounded-xl border border-dashed border-border text-foreground font-semibold">
                Suggestion generation complete. Ready to apply optimal grid layout.
              </div>
              <button onClick={() => { toast.success("AI Suggestions Applied"); setAiModalOpen(false); }} className="w-full mt-6 py-3 bg-indigo-600 text-white font-bold rounded-xl shadow-lg hover:shadow-indigo-500/25 transition-all">
                Apply Smart Layout
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
